### ISSUE TITLE
Error message displays when i excute 'wasm-pack build'

### ISSUE THREAD

**Issue by lamei1224** [paritytech/stateless-blockchain#5]
i dont know how to solve this problem,so i want  someone to help me please.

1. I have installed rust version
2. when i execute 'wasm-pack build' in https://github.com/paritytech/stateless-blockchain on accumulator-client
3. Error Message displays
![error message](https://user-images.githubusercontent.com/55862430/84583797-64705200-ae2f-11ea-961e-661b6964c89f.png)

**Comment by andrewtam** [comment]
Did you try using Nightly Rust (command: "rustup default nightly")? Also, just a disclaimer that this repository will not be updated and is almost certainly outdated already.

**Comment by lamei1224** [comment]
yes，i use the nightly. but i want to try,i am so interested in stateless blockchain,i really want to execute the code ,please help me
![version](https://user-images.githubusercontent.com/55862430/84584026-2fb1ca00-ae32-11ea-8ec6-eee7adf27a12.png)

**Comment by andrewtam** [comment]
Hmm, I don't really know what's causing the error but I suspect that the repository might not be able to handle newer versions of Rust/Cargo. Sorry to do this but I am closing the issue since this repository is deprecated and I no longer work for Parity.

**Comment by andrewtam** [comment]
Hmm, I don't really know what's causing the error but I suspect that the repository might not be able to handle newer versions of Rust/Cargo. Sorry to do this but I am closing the issue since this repository is deprecated and I no longer work for Parity.

**Comment by lamei1224** [comment]
Although the author has not updated the code, can someone help me solve this problem?thank you very much！
